### ISSUE TITLE
Integration into Elastic v5.X?

### ISSUE THREAD

**Issue by wirecutter313** [graphaware/graph-aided-search#11]
Does this work with version 5? 

Any roadblocks or issues?

**Comment by ikwattro** [comment]
This doesn't yet and we don't have an ETA yet for when it will be available for ES 5.x

**Comment by wirecutter313** [comment]
Anything we can do to help?

**Comment by hailiang-wang** [comment]
+1

**Comment by hailiang-wang** [comment]
I am going to do some work with this requirement. 
https://github.com/Samurais/graph-aided-search/tree/es5

@wirecutter313 maybe we can work together.

**Comment by zdobrenen** [comment]
Has there been any commitment to this integration? Very interested in graph-aided-search with es5

**Comment by hailiang-wang** [comment]
Sorry, after reading the sourcecode, I would say, it needs a lot efforts, so I fallback to v2.

**Comment by sonu27** [comment]
I'd say skip ES5 and go to ES6
