### ISSUE TITLE
I  meet "Neo.ClientError.Security.Unauthorized",when i integrated neo4j3.1.3 and ES2.2.2

### ISSUE THREAD

**Issue by goat98** [graphaware/graph-aided-search#12]
sent request "curl -X POST http://localhost:9200/neo4j-index/Movie/_search -d '{
  "query" : {
      "bool": {
        "should": [{"match": {"title": "love"}}]
      }
  },
  "gas-filter" :{
      "name": "SearchResultCypherFilter",
      "query": "MATCH (n:User)-[r:LIKES]->(m) WITH m, avg(r.rate) as avg_rate where avg_rate < 3 RETURN m.objectId as id",
      "exclude": true,
      "keyProperty": "objectId"
  }
}'"

get an error : "{"error":{"root_cause":[{"type":"runtime_exception","reason":"Failed to parse a search response."}],"type":"runtime_exception","reason":"Failed to parse a search response.","caused_by":{"type":"runtime_exception","reason":"Cypher Execution Error, message is : {code=Neo.ClientError.Security.Unauthorized, message=No authentication header supplied.}"}},"status":500}"

first,i wouldn't setting   dbms.security.auth_enabled=false,
help me!!!!

**Comment by goat98** [comment]
if i set  dbms.security.auth_enabled=false, response success.for security ,i don,t.

**Comment by vince-bickers** [comment]
You need to send username and password in your cURL request. https://stackoverflow.com/questions/2594880/using-curl-with-a-username-and-password

**Comment by vince-bickers** [comment]
Please see the project README on how to do this:

https://github.com/graphaware/graph-aided-search
