### ISSUE TITLE
Elastic v2.4.6 support and release

### ISSUE THREAD

**Issue by zdobrenen** [graphaware/graph-aided-search#17]
Will there be a future release to support Elastic v2.4.6 as there are bug fixes to ES since v2.4.4? Also, the readme says v2.4.4 is supported but there is no release for that version. Will this be available soon?

**Comment by gbahrani** [comment]
I plan to use Graph Aided Search at MeTripping (travel search engine), but don't find a usable version available. I am using 2.4.6 ES (as that's what is recommended by ES and is available as docker container) but don't have matching Graph Aided Search version. I tried compiling the code but it didn't work; below is the error which I see

[ERROR] Command was /bin/sh -c cd /home/graph-aided-search/graph-aided-search && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx2048m -XX:MaxPermSize=512m -jar /home/graph-aided-search/graph-aided-search/target/surefire/surefirebooter5999656005816994393.jar /home/graph-aided-search/graph-aided-search/target/surefire 2017-11-06T01-39-13_375-jvmRun1 surefire5555579431605074443tmp surefire_03577268448340354196tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] com.graphaware.es.gas.booster.SearchResultCypherBoosterTest
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:686)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] at org.apache.maven.plugin
