### ISSUE TITLE
 No new recod in Elastic

### ISSUE THREAD

**Issue by scale-logic** [graphaware/graph-aided-search#18]
Hello, i tried run module, but i have not seen any changes in elastic.
What i did:
1. I have windows and i put jar into 
```
~\Documents\Neo4j\default.graphdb\plugins
```
2. Change config - add to row 
```
elasticsearch.host_name=http://localhost:9200
elasticsearch.index_spec=people:Person(name).
```
My elastic used this default port .

3. Than run elastic and neo4j. 

4. I used 
```
CREATE (ee:Person {name: "Emil"})
```
5.  used 
```
MATCH (ee:Person) WHERE ee.name = "Emil" SET ee.name= ee.name
```
6. After that i called 
```
curl -XGET localhost:9200/* and get nothing
```
Why my command 
```
MATCH (ee:Person) WHERE ee.name = "Emil" SET ee.name= ee.name cannot create ne record in elastic
```

Configuration:
1. Windows 10
2. elastic 5.6
3. Neo4j 3.2.5

**Comment by ikwattro** [comment]
Hi, this plugin is an Elasticsearch plugin, not a neo4j one. You might want to check https://github.com/graphaware/neo4j-to-elasticsearch instead.

**Comment by scale-logic** [comment]
Thanks, sorry about this question
