### ISSUE TITLE
Integrating neo4j 3.0.3 and es 2.3.2

### ISSUE THREAD

**Issue by vvavepacket** [graphaware/graph-aided-search#2]
Hi:

I tried following the steps outlined here.

http://graphaware.com/neo4j/2016/04/20/graph-aided-search-the-rise-of-personalised-content.html

The website uses older neo4j version which is 2.x,, so I replaced all downloads with neo4j 3.x

Now, I'm currently at the step where we are to Configure Graph-Aided Search by defining the URL of the Neo4j server instance and enabling it.

When we execute the following command:

`$ curl -XPUT "http://localhost:9200/neo4j-index/_settings?index.gas.neo4j.hostname=http://localhost:7474&index.gas.enable=true"`

we got the following error:

`{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"neo4j-index","index":"neo4j-index"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"neo4j-index","index":"neo4j-index"},"status":404}`

**Comment by ikwattro** [comment]
Hi @vvavepacket Sorry I missed this issue in my timeline.

Did you created the elasticsearch index beforehand ?

**Comment by vvavepacket** [comment]
No. I was expecting the plugin to do it for me.. Is that the way by default?

**Comment by ikwattro** [comment]
@vvavepacket The `neo4j-to-elasticsearch` will attempt to create the index when you start neo4j with this plugin enabled.

The `graph-aided-search` plugin will not attempt to create the index.

You can just create the index with curl : 

```
curl -XPUT 'http://localhost:9200/neo4j-index' 
```

**Comment by vvavepacket** [comment]
Thanks.

**Comment by linoan** [comment]
Hi,
I'm not sure if you encountered it but, in neo4j the configuration changed and the guide only works for neo4j 2.x
I tried doing this for neo4j 3.x and it wasnt able to load the plugin.

#org.neo4j.server.thirdparty_jaxrs_classes=com.graphaware.server=/graphaware
dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware

Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@1a4d0b0' failed to initialize. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:416)

**Comment by cseppd** [comment]
I created the index, but not get any success hit with neo4j data search
    {
        "took": 24,
        "timed_out": false,
        "_shards":
        {
            "total": 5,
            "successful": 5,
            "failed": 0
        },
        "hits":
        {
            "total": 0,
            "max_score": null,
            "hits":
            [
            ]
        }
    }

Plz help ......

**Comment by dchatterjee172** [comment]
@ikwattro 
I am facing the same problem as @cseppd  explained.
output of any query is   `{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
`   
output of `curl -X GET "localhost:9200/_cat/indices?v" `   
is   
`yellow open   neo4j-index   5   1          0            0       795b           795b`   
where docs.count is 0   
i have already configured the plugin using    `curl -XPUT 'http://localhost:9200/neo4j-index/' -d '{
    "settings" : {
        "index.gas.neo4j.hostname" : "http://localhost:7474",
        "index.gas.enable" : true
    }
}'`   
in the browser `http://localhost:9200/neo4j-index/`   gives output   
`{"neo4j-index":{"aliases":{},"mappings":{},"settings":{"index":{"gas":{"enable":"true","neo4j":{"hostname":"http://localhost:7474"}},"creation_date":"1526953191102","number_of_shards":"5","number_of_replicas":"1","uuid":"eCQWEqTpRXGb1hUdttYWog","version":{"created":"2020299"}}},"warmers":{}}}`

**Comment by ikwattro** [comment]
@dchatterjee172 @cseppd Do you have any data in your Elasticsearch index ?

**Comment by dchatterjee172** [comment]
@ikwattro    
I don't think so as output of `curl -X GET "localhost:9200/_cat/indices?v"` is   
`yellow open neo4j-index 5 1 0 0 795b 795b`   
where docs.count is 0   
elasticsearch has successfully created the primary shards but there is no document in those shards

**Comment by ikwattro** [comment]
Ok, so what are your expectations if you don't have documents ?

**Comment by dchatterjee172** [comment]
@ikwattro 
as the data is already loaded in neo4j and gas extensions are also present in both elasticsearch and neo4j, shouldn't I able to query and get result?

**Comment by ikwattro** [comment]
the data should first be replicated from neo4j to ES. 

check neo4j-to-elasticsearch for this

**Comment by dchatterjee172** [comment]
@ikwattro isn't that already configured in the demo container?

**Comment by ikwattro** [comment]
Yes, if you kept exactly the same versions of plugins and neo4j. So please confirm you run neo4j 2.3.2 which is 2 years old.

If you run the exact same docker-compose of this repository, then you should see logs when you start importing the data into neo4j, please paste them here.

**Comment by ikwattro** [comment]
If you upgraded to a more recent neo4j, then the `neo4j-to-elasticsearch` plugin has evolved a lot. And this demo is not aligned with them

**Comment by dchatterjee172** [comment]
@ikwattro 
These are the logs when I use docker-compose
`Starting elastic_container ... done
Starting neo4j             ... done
Attaching to neo4j, elastic_container
neo4j      | WARNING: Max 1024 open files allowed, minimum of 40 000 recommended. See the Neo4j manual.
neo4j      | Starting Neo4j Server console-mode...
elastic_container | [2018-05-22 13:43:24,850][WARN ][bootstrap                ] unable to install syscall filter: seccomp unavailable: your kernel is buggy and you should upgrade
elastic_container | [2018-05-22 13:43:25,394][INFO ][node                     ] [Ramrod] version[2.2.2], pid[1], build[fcc01dd/2016-03-29T08:49:35Z]
elastic_container | [2018-05-22 13:43:25,394][INFO ][node                     ] [Ramrod] initializing ...
elastic_container | [2018-05-22 13:43:26,760][INFO ][plugins                  ] [Ramrod] modules [lang-expression, lang-groovy], plugins [graph-aided-search], sites []
elastic_container | [2018-05-22 13:43:26,809][INFO ][env                      ] [Ramrod] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/mapper/luks-b5afbe83-acdc-49fd-958d-03f728d8daf4)]], net usable_space [184gb], net total_space [216.4gb], spins? [possibly], types [ext4]
elastic_container | [2018-05-22 13:43:26,810][INFO ][env                      ] [Ramrod] heap size [990.7mb], compressed ordinary object pointers [true]
neo4j      | 2018-05-22 13:43:27.013+0000 INFO  Initiating metrics..
elastic_container | [2018-05-22 13:43:32,244][INFO ][node                     ] [Ramrod] initialized
elastic_container | [2018-05-22 13:43:32,244][INFO ][node                     ] [Ramrod] starting ...
elastic_container | [2018-05-22 13:43:32,723][INFO ][transport                ] [Ramrod] publish_address {172.18.0.3:9300}, bound_addresses {0.0.0.0:9300}
elastic_container | [2018-05-22 13:43:32,754][INFO ][discovery                ] [Ramrod] docker/PFFUboB2Qhu_De14C9z2GQ
neo4j      | 2018-05-22 13:43:34.965+0000 INFO  Successfully started database
neo4j      | 2018-05-22 13:43:35.007+0000 INFO  Starting HTTP on port 7474 (4 threads available)
neo4j      | 2018-05-22 13:43:35.271+0000 INFO  Enabling HTTPS on port 7473
neo4j      | 2018-05-22 13:43:35.276+0000 INFO  Mounted REST API at: /db/manage
neo4j      | 2018-05-22 13:43:35.305+0000 INFO  Mounted unmanaged extension [com.graphaware.server] at [/graphaware]
neo4j      | 2018-05-22 13:43:35.400+0000 INFO  Mounting static content at /webadmin
neo4j      | 2018-05-22 13:43:35.490+0000 INFO  Mounting static content at /browser
elastic_container | [2018-05-22 13:43:35,869][INFO ][cluster.service          ] [Ramrod] new_master {Ramrod}{PFFUboB2Qhu_De14C9z2GQ}{172.18.0.3}{172.18.0.3:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
elastic_container | [2018-05-22 13:43:35,954][INFO ][http                     ] [Ramrod] publish_address {172.18.0.3:9200}, bound_addresses {0.0.0.0:9200}
elastic_container | [2018-05-22 13:43:35,955][INFO ][node                     ] [Ramrod] started
elastic_container | [2018-05-22 13:43:36,291][INFO ][gateway                  ] [Ramrod] recovered [1] indices into cluster_state
elastic_container | [2018-05-22 13:43:37,955][INFO ][cluster.routing.allocation] [Ramrod] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[neo4j-index][1]] ...]).
neo4j      | 2018-05-22 13:43:40.774+0000 INFO  Remote interface ready and available at http://0.0.0.0:7474/
`

**Comment by ikwattro** [comment]
Great, but there should be logs once you start importing the dataset as explained in the demo repository

**Comment by dchatterjee172** [comment]
@ikwattro do you mean the cypher queries by "importing"?

**Comment by dchatterjee172** [comment]
you can see the version here @ikwattro    
https://imgur.com/a/zN7M9FV     
and i can see nodes and relationship also

**Comment by ikwattro** [comment]
Can you explain in clear 

What type of data you have inserted ( there is no data loaded in advance so in our demo, you have to import yourself a specific dataset

Make a screenshot of the nodes and relationships you have

**Comment by dchatterjee172** [comment]
@ikwattro 
https://imgur.com/a/H3Wgirl
