### ISSUE TITLE
Is this deprecated?

### ISSUE THREAD

**Issue by bionicles** [graphaware/graph-aided-search#21]
Hi,

This is a useful concept because it can improve understanding of complex networks... do you plan to come back to it?

Just curious because I prefer active codebases!

**Comment by panamantis** [comment]
I'm not fully familiar with this codebase but the neo4j team is active.  Have a look at their NLP pipeline [https://github.com/graphaware/neo4j-nlp](https://github.com/graphaware/neo4j-nlp) or other elastic search interface at https://github.com/graphaware/neo4j-to-elasticsearch

**Comment by johanwasserman** [comment]
@ikwattro is graph-aided-search dead or will it still work with Neo4J 3.x & Elasticsearch >= 7?

**Comment by viveknimkarde** [comment]
It's very disappointing to see this package not being maintained with current developments
+1
