### ISSUE TITLE
Multi-index query with the plugin

### ISSUE THREAD

**Issue by lioryaffe** [graphaware/graph-aided-search#4]
Is the gas-filter should support a multi-type query? 
something like GET index1,index2/_search
?

**Comment by ikwattro** [comment]
I didn't tried that yet as my experience with multi indexes query is that it performs really bad, but there is no reason I can see why it wouldn't work. Please test it and report if working or not

**Comment by lioryaffe** [comment]
It doesn't work...i took a cypher and ran a gas-filter on index1 and it worked, on index2 and it worked but when tested on index1,index2 i'm getting:

      "failed_shards": [
         {
            "shard": 0,
            "index": "index2",
            "node": "llCYV-WaQv2W_K2NMuMHVQ",
            "reason": {
               "type": "search_parse_exception",
               "reason": "failed to parse search source. unknown search element [gas-filter]",
               "line": 38,
               "col": 4
            }
         }
      ]

**Comment by ikwattro** [comment]
Thanks we will investigate that.

Just to confirm, you created the graph-aided-search settings on all indexes
right?

**Comment by lioryaffe** [comment]
yep

**Comment by orirubinfeld** [comment]
Hi,

We are experiencing the same issue, and would like to use the GAS-FILTER with Multi-Indexes query.
Do you have any progress with it ?

Thanks,

Ori

**Comment by ikwattro** [comment]
No progress on it. This will be tackled once we can allocate time on it.
