### ISSUE TITLE
SearchResultCypherFilter Filtering Everything on Very Simple Query

### ISSUE THREAD

**Issue by daviddyball** [graphaware/graph-aided-search#8]
Hi,

We're currently giving GAS ago for filtering search queries based on information returned from the graph. It's all very simple, so I'm not sure why it's not working. If I add ```"exclude": true``` to the query it does return results that *don't* match, like I would expect. As crazy as it sounds, if I run the graph query manually and run the search without the `gas-filter` clause, I can see the documents returned *do* contain the `id`s of the documents that are returned by the Cypher query. I'm stumped. Any help you could provide would be appreciated.

### Graph Layout
`(:Product {id: <int>})-[:SIMILAR_TO {weight: <int>}]->(other:Product)`

### Search Mapping
```
GET /products/product/_mapping
{
  "products" : {
    "mappings" : {
      "product" : {
        "properties" : {
          "id" : {
            "type" : "integer"
          }
        }
      }
    }
  }
}
```

Result when running the Cypher query directly
```
> MATCH (:Product {id: 1})-[r:SIMILAR_TO]->(other) RETURN other.id as id ORDER BY r.weight DESC
╒═══╕
│id │
╞═══╡
│ 5 │
├───┤
│ 2 │
├───┤
│ 4 │
├───┤
│ 3 │
└───┘
```

The GAS query that returns nothing:
```
{
  "query": {
    "match_all": {}
  },
  "gas-filter": {
    "query": "MATCH (:Product {id: 1})-[r:SIMILAR_TO]->(other) RETURN other.id as id ORDER BY r.weight DESC",
    "protocol": "bolt",
    "name": "SearchResultCypherFilter"
  },
  "size": 10,
  "fields": ["id"]
}
```

Query Output for above:
```
{
  "took": 602,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  }
}
```

UPDATE: Added verbose logging to ES

```
.......
search_1     | [2017-02-16 16:29:27,934][DEBUG][com.graphaware.es.gas.wrap.WrappingActionListener] [Brass] Boosting results: {
search_1     |   "took" : 14,
search_1     |   "timed_out" : false,
search_1     |   "_shards" : {
search_1     |     "total" : 5,
search_1     |     "successful" : 5,
search_1     |     "failed" : 0
search_1     |   },
search_1     |   "hits" : {
search_1     |     "total" : 1,
search_1     |     "max_score" : 7.918695,
search_1     |     "hits" : [ {
search_1     |       "_index" : "products",
search_1     |       "_type" : "product",
search_1     |       "_id" : "636279",
search_1     |       "_score" : 7.918695,
search_1     |       "fields" : {
search_1     |         "id" : [ 636279 ]
search_1     |       }
search_1     |     } ]
search_1     |   }
search_1     | }
search_1     | [2017-02-16 16:29:27,935][DEBUG][com.graphaware.es.gas.wrap.WrappingActionListener] [Brass] Reading headers...
search_1     | [2017-02-16 16:29:27,935][DEBUG][com.graphaware.es.gas.wrap.WrappingActionListener] [Brass] Reading hits...
search_1     | [2017-02-16 16:29:27,981][DEBUG][com.graphaware.es.gas.wrap.WrappingActionListener] [Brass] Reading aggregations...
search_1     | [2017-02-16 16:29:27,981][DEBUG][com.graphaware.es.gas.wrap.WrappingActionListener] [Brass] Reading suggest...
search_1     | [2017-02-16 16:29:27,981][DEBUG][com.graphaware.es.gas.wrap.WrappingActionListener] [Brass] Creating new SearchResponse...
search_1     | [2017-02-16 16:29:27,981][DEBUG][com.graphaware.es.gas.wrap.WrappingActionListener] [Brass] Rewriting overhead time: 62 - 14 = 48ms
.......
```

**Comment by ikwattro** [comment]
Seems like it is using a booster. Can you specify the version of the plugin you are using so I can test locally ? THanks

**Comment by daviddyball** [comment]
Elasticsearch `2.4.1` and GAS `2.4.1.3`

**Comment by daviddyball** [comment]
@ikwattro Any luck recreating the issue?

**Comment by ikwattro** [comment]
Hi @daviddyball 

Yes I could reproduce this. I have two things to say : 

1. The `exclude` doesn't exist, the name of the key is `shoudExclude` : 

```
{
  "query": {
    "match_all": {}
  },
  "gas-filter": {
    "query": "MATCH (p:Product) WHERE p.id IN [2,3,4] RETURN p.id AS id",
    "name": "SearchResultCypherFilter",
    "shouldExclude": true
  }
}
```

Which returns me 0 results also : 

```
ikwattro@graphaware-team ~/dev> http POST "http://localhost:9200/nodes/_search" < gasq1.json
HTTP/1.1 200 OK
Content-Length: 123
Content-Type: application/json; charset=UTF-8

{
    "_shards": {
        "failed": 0,
        "successful": 5,
        "total": 5
    },
    "hits": {
        "hits": [],
        "max_score": 0.0,
        "total": 0
    },
    "timed_out": false,
    "took": 162
}

ikwattro@graphaware-team ~/dev>
```

2. I'm not sure how you expect the comparison from the ES docs to be done against the neo4j nodes. 

There should be a similitude between ES `_ids` and Neo4j ids. 

We have no way to compare an ES `field` against a neo4j unique id as there is not certitude of uniqueness outside of the `_id` in the document.

This means that returning from Neo4j something like this : 


```

MATCH (p:Product) WHERE p.id IN [2,3,4] RETURN p.id AS id

╒════╕
│"id"│
╞════╡
│2   │
├────┤
│3   │
├────┤
│4   │
└────┘
```

Your ES document _ids should have an _id corresponding to `2, 3 and 4` . 


Changing my query to return uuids of the nodes instead (that match document _ids in ES), I can see that the plugin is behaving correctly now : 

```
{
  "query": {
    "match_all": {}
  },
  "gas-filter": {
    "query": "MATCH (p:Product) WHERE p.id IN [2,3,4] RETURN p.uuid AS id",
    "name": "SearchResultCypherFilter",
    "shouldExclude": true
  }
}
```

```
{
    "_shards": {
        "failed": 0,
        "successful": 5,
        "total": 5
    },
    "hits": {
        "hits": [
            {
                "_id": "e0529a51-f76b-11e6-a897-0a73b7c8b72d",
                "_index": "nodes",
                "_score": 1.0,
                "_source": {
                    "_labels": [
                        "Product"
                    ],
                    "id": 4,
                    "title": "Product4",
                    "uuid": "e0529a51-f76b-11e6-a897-0a73b7c8b72d"
                },
                "_type": "node"
            },
            {
                "_id": "e0527340-f76b-11e6-a897-0a73b7c8b72d",
                "_index": "nodes",
                "_score": 1.0,
                "_source": {
                    "_labels": [
                        "Product"
                    ],
                    "id": 2,
                    "title": "Product2",
                    "uuid": "e0527340-f76b-11e6-a897-0a73b7c8b72d"
                },
                "_type": "node"
            },
            {
                "_id": "e0529a50-f76b-11e6-a897-0a73b7c8b72d",
                "_index": "nodes",
                "_score": 1.0,
                "_source": {
                    "_labels": [
                        "Product"
                    ],
                    "id": 3,
                    "title": "Product3",
                    "uuid": "e0529a50-f76b-11e6-a897-0a73b7c8b72d"
                },
                "_type": "node"
            }
        ],
        "max_score": 1.0,
        "total": 3
    },
    "timed_out": false,
    "took": 147
}
```

**Comment by daviddyball** [comment]
Hi again,

Thank you for coming back to me on this. I really appreciate it. It's odd though, as our `_id` fields in Elasticsearch are identical to the `id` properties of our Nodes in Neo4J. They all come from row unique-id's in our main app database, so there is definite uniqueness about them and it should be fairly consistent across the DB, Graph and Index. Any thoughts?

Thank

**Comment by ikwattro** [comment]
@daviddyball  Ok I "hope" I know then. _ids in ES are strings ;-)

Change your query to `RETURN toString(other.id) as id ORDER BY r.weight DESC` ?

**Comment by daviddyball** [comment]
I just tried with `toString(n.id)` and can confirm it is returning strings to ES, but unfortunately the filter portion is still returning zero results, even though it should return ~200 or so in my example data set. I'll keep having a poke around and see  what I can come up with.

**Comment by ikwattro** [comment]
Allright, if you are able to export an ES backup as well as a neo4j zip, I might be able to have a look as well. Feel free to do so : christophe (at) graphaware (dot) com

**Comment by ikwattro** [comment]
@daviddyball Any update on this. I'm keen to help further if you can provide us some data even anonamysed.

**Comment by daviddyball** [comment]
Hi @ikwattro, I was unable to get it working with `toString()` for the returned `id`s, which was odd. Our dataset is pretty big, so I tried to mimic it with a much smaller dataset, but unfortunately time got away from me. I will spend some time on it now and send you over a copy of the data. Thank you again for all you help.

**Comment by ikwattro** [comment]
You can maybe export to json the ES results of your query without GAS as well as exporting the graph result returned by the query with the shell for eg : 

```
./bin/neo4j-shell -c dump ' MATCH (n:Product {id:1})-[r:SIMILAR_TO]->(other) RETURN n, r, other' > result.cypher
```

**Comment by daviddyball** [comment]
Wow, that makes things way easier. I'll do that and send it on over.

**Comment by daviddyball** [comment]
**Update**: After reviewing a test data-set @ikwattro and I been unable to recreate the problems I was seeing earlier. I believe it may be a problem in the original implementation, so I'll mark this as closed unless something comes up in future.

Thanks @ikwattro
