### ISSUE TITLE
Is this framework compatible with Elasticsearch 5.0 and Neo4J 3.1.1?

### ISSUE THREAD

**Issue by rumilshah** [graphaware/graph-aided-search#9]

**Comment by ikwattro** [comment]
With neo4j 3.1 yes as it makes remote requests to neo4j. It is not compatible with ES 5.0.

**Comment by rumilshah** [comment]
Can you provide any timeline that when it will be available? We are using ES 5.1.2.

**Comment by ikwattro** [comment]
Not really, every ES version (even minor) introduces a lot of breaking changes. ES 5.0 is quite a huge rewrite of the internal APIs and it will require us a serious amount of time to upgrade as well as it is dependent of our work load.
